/* Offline React UI. React is vendored; no CDN or runtime package downloads. */
declare const React:any, ReactDOM:any, FlockMath:any;
const M=FlockMath;
const money=(n:any,dp=0)=>n===null||n===undefined||!Number.isFinite(n)?'—':'₱'+n.toLocaleString('en-PH',{minimumFractionDigits:dp,maximumFractionDigits:dp});
const qty=(n:any,dp=2)=>n===null||n===undefined||!Number.isFinite(n)?'—':n.toLocaleString('en-PH',{maximumFractionDigits:dp,minimumFractionDigits:dp});
const dateLabel=(s:any)=>M.validDate(s)?new Date(s+'T12:00:00').toLocaleDateString('en-PH',{day:'numeric',month:'short',year:'numeric'}):'Date unknown';
const clone=(s:any)=>JSON.parse(JSON.stringify(s));
const NATIVE=typeof navigator!=='undefined' && navigator.userAgent.indexOf('FlockLedger/1')>=0;
function nativeCall(op:string,data=''){return window.prompt('flock:'+op,data);}
function storeRead(){return NATIVE?nativeCall('load'):localStorage.getItem('flock-ledger-v1');}
function storeWrite(s:any){const text=JSON.stringify(s);if(text.length>4500000)throw new Error('The local ledger is near its 4.5 MB limit. Export a backup before removing old batches.');if(NATIVE){if(nativeCall('save',text)!=='ok')throw new Error('Android storage could not save the change. Your previous data has been kept.');}else localStorage.setItem('flock-ledger-v1',text);}
function saveDownload(name:string,text:string,mime='application/json'){if(NATIVE){const result=nativeCall('export',JSON.stringify({name,mime,text}));if(result!=='pending')throw new Error(result||'Export was not started.');return;}const u=URL.createObjectURL(new Blob([text],{type:mime}));const a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),3000);}
const ICONS:any={home:'M3 11l9-8 9 8M5 10v11h5v-7h4v7h5V10',log:'M5 3h14v18H5zM9 7h6M9 11h6M9 15h4',chart:'M4 4v16h17M7 15l4-5 4 2 5-7',flock:'M5 19v-5a7 7 0 0114 0v5M8 20h8M8 8V5h8v3',save:'M5 3h12l3 3v15H4V3zM8 3v6h8V3M8 21v-7h8v7',plus:'M12 5v14M5 12h14',arrow:'M5 12h14M14 7l5 5-5 5',close:'M6 6l12 12M18 6L6 18',edit:'M4 20l4-1 12-12-4-4L4 15v5M14 5l4 4',down:'M6 9l6 6 6-6',check:'M5 12l4 4L19 6',feed:'M5 7h14l2 14H3L5 7zM8 3h8M12 11v6',weight:'M5 8h14l2 13H3L5 8zM9 8V5a3 3 0 016 0v3',trash:'M4 6h16M9 6V3h6v3M6 6l1 15h10l1-15M10 10v7M14 10v7',info:'M12 11v6M12 7v.1M22 12a10 10 0 11-20 0 10 10 0 0120 0'};
function Icon({name,size=20}:any){return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.65" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={ICONS[name]||ICONS.log}/></svg>;}
function Badge({children,kind='muted'}:any){return <span className={'badge '+kind}>{children}</span>;}
function Note({children,tone='info'}:any){return <div className={'note '+tone}><Icon name="info" size={17}/><div>{children}</div></div>;}
function Field({label,hint,children,wide=false}:any){return <label className={'field '+(wide?'wide':'')}><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>;}
function Metric({label,value,sub,accent=false}:any){return <div className={'metric '+(accent?'accent':'')}><span className="eyebrow">{label}</span><strong>{value}</strong><small>{sub}</small></div>;}
function Empty({title,text,action}:any){return <div className="empty"><Icon name="chart" size={30}/><h3>{title}</h3><p>{text}</p>{action}</div>;}
function SectionTitle({title,sub,action}:any){return <div className="section-heading"><div><h2>{title}</h2>{sub&&<p>{sub}</p>}</div>{action}</div>;}
function LineChart({series,title,unit='kg',xLabel='Days since purchase',floorZero=false}:any){
  const all=series.reduce((a:any,s:any)=>a.concat(s.points),[]).filter((p:any)=>Number.isFinite(p.x)&&Number.isFinite(p.y));
  if(!all.length)return <Empty title="No chart data yet" text="Add a dated record to begin."/>;
  const W=720,H=285,L=64,R=25,T=20,B=46;
  let minX=Math.min(...all.map((p:any)=>p.x)), maxX=Math.max(...all.map((p:any)=>p.x));if(minX===maxX){minX-=1;maxX+=1;}
  let minY=floorZero?0:Math.min(...all.map((p:any)=>p.y)),maxY=Math.max(...all.map((p:any)=>p.y));let delta=maxY-minY||Math.max(1,maxY*.2);if(!floorZero)minY=Math.max(0,minY-delta*.12);maxY+=delta*.15;if(maxY===minY)maxY=minY+1;
  const x=(v:number)=>L+(v-minX)/(maxX-minX)*(W-L-R), y=(v:number)=>H-B-(v-minY)/(maxY-minY)*(H-T-B);
  const yfmt=(n:number)=>unit==='₱/kg'?'₱'+n.toFixed(0):n.toFixed(maxY<5?1:0);
  return <div className="chart"><div className="chart-legend">{series.map((s:any,i:number)=><span key={i}><i className={s.dash?'dashed':''} style={{borderColor:s.color}}/>{s.label}</span>)}</div><svg viewBox={`0 0 ${W} ${H}`} role="img" aria-label={title+'; '+unit+' by '+xLabel}>
    {[0,1,2,3,4].map(i=>{const val=minY+(maxY-minY)*i/4;return <g key={i}><line x1={L} x2={W-R} y1={y(val)} y2={y(val)} stroke="#e7e9e2"/><text x={L-11} y={y(val)+4} textAnchor="end" className="axis-text">{yfmt(val)}</text></g>;})}
    {[0,1,2,3,4,5].map(i=>{const val=minX+(maxX-minX)*i/5;return <g key={i}><text x={x(val)} y={H-B+22} textAnchor="middle" className="axis-text">{Math.round(val)}</text></g>;})}
    <line x1={L} x2={W-R} y1={H-B} y2={H-B} stroke="#bac2b5"/>
    {series.map((s:any,i:number)=><g key={i}>{s.connect!==false&&s.points.length>1&&<polyline fill="none" stroke={s.color} strokeWidth="2.7" strokeDasharray={s.dash?'7 6':undefined} points={s.points.map((p:any)=>`${x(p.x)},${y(p.y)}`).join(' ')}/>} {s.points.filter((p:any,j:number)=>s.markAll||s.points.length<5||j===0||j===s.points.length-1).map((p:any,j:number)=><circle key={j} cx={x(p.x)} cy={y(p.y)} r={s.connect===false?5:3} fill={s.open?'#fff':s.color} stroke={s.color} strokeWidth="2"><title>{`Day ${p.x}: ${unit==='₱/kg'?money(p.y,2):qty(p.y)+' '+unit}`}</title></circle>)}</g>)}
    <text x={(W+L-R)/2} y={H-3} textAnchor="middle" className="axis-text">{xLabel}</text>
  </svg><small className="chart-caption">{unit==='₱/kg'?'Focused vertical scale for comparing cost differences. ':''}Exact values are shown in the records or comparison table below.</small></div>;
}
class RecordForm extends React.Component<any,any>{
  constructor(props:any){super(props);const e=props.event||{},t=props.type||e.type||'weigh';this.state={type:t,date:e.date===null?'':e.date||M.today(),name:e.name||'',phase:e.phase||'finisher',cost:e.cost===undefined?'':String(e.cost),kg:e.kg===null||e.kg===undefined?'':String(e.kg),lotId:e.lotId||'',startDate:e.startDate||M.addDays(M.today(),-1),avgKg:e.avgKg===undefined?'':String(e.avgKg),minKg:e.minKg===null||e.minKg===undefined?'':String(e.minKg),maxKg:e.maxKg===null||e.maxKg===undefined?'':String(e.maxKg),sampleN:e.sampleN===null||e.sampleN===undefined?'':String(e.sampleN),method:e.method||'measured',weights:e.weights?e.weights.join(', '):'',count:e.count===undefined?'':String(e.count),liveKg:e.liveKg===null||e.liveKg===undefined?'':String(e.liveKg),dressedKg:e.dressedKg===undefined?'':String(e.dressedKg),revenue:e.revenue===undefined?'0':String(e.revenue),homeKg:e.homeKg===undefined?'0':String(e.homeKg),note:e.note||'',error:''};}
  set=(k:string,v:any)=>this.setState({[k]:v,error:''});
  input=(k:string,opts:any={})=><input type="number" inputMode="decimal" step="any" min="0" value={this.state[k]} onChange={e=>this.set(k,e.target.value)} {...opts}/>;
  save=(ev:any)=>{ev.preventDefault();const s=this.state,n=(k:string,optional=false)=>s[k]===''?(optional?null:NaN):Number(s[k]);let e:any={id:this.props.event?.id||M.uid(),type:s.type,date:s.date||null,createdAt:this.props.event?.createdAt||new Date().toISOString(),note:s.note};
    if(['feed','expense','budget','openingUsage'].includes(s.type)){e.cost=n('cost');e.name=s.name.trim()||({feed:'Feed purchase',expense:'Batch expense',budget:'Feed budget',openingUsage:'Historical feed used'} as any)[s.type];}
    if(s.type==='feed'){e.kg=n('kg',true);e.phase=s.phase;}
    if(s.type==='usage'){e.kg=n('kg');e.lotId=s.lotId;e.startDate=s.startDate;}
    if(s.type==='weigh'){e.method=s.method;e.avgKg=n('avgKg');e.minKg=n('minKg',true);e.maxKg=n('maxKg',true);e.sampleN=n('sampleN',true);e.weights=null;if(s.weights.trim()){const ws=s.weights.trim().split(/[\s,;]+/).map(Number);if(ws.some((w:number)=>!Number.isFinite(w)||w<=0)){this.setState({error:'Enter individual weights as kilograms separated by commas or spaces.'});return;}e.weights=ws;e.avgKg=M.sum(ws)/ws.length;e.minKg=Math.min(...ws);e.maxKg=Math.max(...ws);e.sampleN=ws.length;e.method='measured';}}
    if(['count','loss','harvest'].includes(s.type))e.count=n('count');
    if(s.type==='harvest'){e.liveKg=n('liveKg',true);e.dressedKg=n('dressedKg');e.revenue=n('revenue');e.homeKg=n('homeKg');}
    if(s.type==='openingUsage')e.kg=n('kg',true);
    if(s.type==='note'){e.name=s.name.trim()||'Farm note';}
    try{this.props.onSave(e);}catch(err:any){this.setState({error:err.message});}
  };
  render(){const s=this.state;const titles:any={weigh:'Record a weighing',feed:'Record a feed purchase',usage:'Log feed used',count:'Record live bird count',loss:'Record birds removed / lost',harvest:'Record a harvest',expense:'Record a batch expense',budget:'Set aside a budget',openingUsage:'Log feed used before tracking',note:'Add a farm note'};
    const lots=this.props.batch.events.filter((e:any)=>e.type==='feed'&&e.kg!==null);
    return <form onSubmit={this.save}><div className="modal-heading"><div><span className="eyebrow">{this.props.event?'EDIT RECORD':'NEW RECORD'}</span><h2>{titles[s.type]}</h2></div><button type="button" className="icon-btn" aria-label="Close form" onClick={this.props.onCancel}><Icon name="close"/></button></div>
    {this.props.convert&&<Note>The budget will be replaced by this purchase when you save. Enter the actual kilograms and amount paid.</Note>}
    <div className="form-grid">
    <Field label="Record type" wide><select value={s.type} disabled={!!this.props.event||!!this.props.convert} onChange={e=>this.set('type',e.target.value)}>{Object.entries(titles).map(([v,l])=><option key={v} value={v}>{l as string}</option>)}</select></Field>
    <Field label={s.type==='usage'?'Period end (inclusive)':'Date'} hint={['feed','expense','budget','openingUsage','note'].includes(s.type)?'Leave empty only when the original date is unknown.':undefined}><input type="date" value={s.date} min={this.props.batch.placementDate} onChange={e=>this.set('date',e.target.value)}/></Field>
    {['feed','expense','budget','openingUsage','note'].includes(s.type)&&<Field label={s.type==='feed'?'Brand / product name':'Description'}><input value={s.name} maxLength={180} placeholder={s.type==='feed'?'e.g. Sarimanok Finisher Pellet':'Description'} onChange={e=>this.set('name',e.target.value)}/></Field>}
    {s.type==='feed'&&<><Field label="Feed stage"><select value={s.phase} onChange={e=>this.set('phase',e.target.value)}>{['starter','grower','finisher','booster','other','unknown'].map(v=><option key={v} value={v}>{v[0].toUpperCase()+v.slice(1)}</option>)}</select></Field><Field label="Total kilograms purchased" hint="All sacks combined. Leave blank when unknown.">{this.input('kg',{placeholder:'e.g. 100'})}</Field></>}
    {['feed','expense','budget','openingUsage'].includes(s.type)&&<Field label={s.type==='openingUsage'?'Cost of feed already USED (₱)':'Total amount (₱)'} hint={s.type==='openingUsage'?'Not a new payment; must already appear in feed purchases.':undefined}>{this.input('cost',{required:true,placeholder:'e.g. 3000'})}</Field>}
    {s.type==='feed'&&Number(s.kg)>0&&s.cost!==''&&<div className="field"><span>Calculated price</span><strong className="calculated">{money(Number(s.cost)/Number(s.kg),2)} / kg</strong><small>{money(Number(s.cost)/Number(s.kg)*50)} per 50 kg equivalent</small></div>}
    {s.type==='usage'&&<><Field label="Period start (exclusive)"><input type="date" value={s.startDate} min={this.props.batch.placementDate} onChange={e=>this.set('startDate',e.target.value)}/></Field><Field label="Which purchase / feed lot?" wide><select value={s.lotId} onChange={e=>this.set('lotId',e.target.value)} required><option value="">Select a feed purchase</option>{lots.map((p:any)=><option key={p.id} value={p.id}>{p.name} · {dateLabel(p.date)} · {qty(p.kg)} kg bought</option>)}</select></Field><Field label="Kilograms used in this period" hint="Include feed lost at the feeder. Unused stock stays in inventory.">{this.input('kg',{required:true})}</Field>{lots.length===0&&<div className="wide"><Note tone="warn">Add a feed purchase with a known kilogram quantity first.</Note></div>}</>}
    {s.type==='weigh'&&<><Field label="Measurement quality"><select value={s.method} onChange={e=>this.set('method',e.target.value)}><option value="measured">Weighed sample</option><option value="estimate">Rough estimate only</option></select></Field><Field label="Individual weights (kg)" wide hint="Optional. Commas or spaces; average, range and sample count are calculated."><textarea rows={2} placeholder="0.98, 1.04, 1.10, 0.95" value={s.weights} onChange={e=>this.set('weights',e.target.value)}/></Field><Field label="Average live weight (kg)">{this.input('avgKg',{disabled:!!s.weights.trim(),required:!s.weights.trim()})}</Field><Field label="Number of birds weighed">{this.input('sampleN',{step:1,disabled:!!s.weights.trim(),required:s.method==='measured'&&!s.weights.trim()})}</Field><Field label="Smallest bird (kg, optional)">{this.input('minKg',{disabled:!!s.weights.trim()})}</Field><Field label="Largest bird (kg, optional)">{this.input('maxKg',{disabled:!!s.weights.trim()})}</Field></>}
    {['count','loss','harvest'].includes(s.type)&&<Field label={s.type==='count'?'Birds actually alive and present':s.type==='harvest'?'Birds harvested':'Birds lost / removed'} hint={s.type==='count'?'A count is a snapshot, not a number to subtract.':undefined}>{this.input('count',{step:1,required:true})}</Field>}
    {s.type==='harvest'&&<><Field label="Total live weight (kg, optional)">{this.input('liveKg')}</Field><Field label="Total dressed weight (kg)">{this.input('dressedKg',{required:true})}</Field><Field label="Cash received for this harvest (₱)" hint="Use 0 for home consumption; not a retail-equivalent estimate.">{this.input('revenue',{required:true})}</Field><Field label="Dressed kg kept for home">{this.input('homeKg',{required:true})}</Field></>}
    {s.type==='openingUsage'&&<><div className="wide"><Note tone="warn">Use only for feed used before detailed tracking. Do not also log the same feed as lot usage. This entry adds production cost, not another cash payment.</Note></div><Field label="Historical kg used (optional)">{this.input('kg')}</Field></>}
    <Field label="Notes" wide><textarea rows={3} maxLength={5000} value={s.note} onChange={e=>this.set('note',e.target.value)} placeholder="Supplier, feed quality, flock health, or anything worth remembering."/></Field>
    </div>{s.error&&<Note tone="error">{s.error}</Note>}<div className="modal-actions"><button type="button" className="btn secondary" onClick={this.props.onCancel}>Cancel</button><button type="submit" className="btn primary"><Icon name="check"/>Save record</button></div></form>;
  }
}
class BatchForm extends React.Component<any,any>{
  constructor(props:any){super(props);const b=props.batch;this.state={name:b?.name||'',placementDate:b?.placementDate||M.today(),initialBirds:b?.initialBirds||'',chickCost:b?.chickCost===undefined?'':b.chickCost,ageAtPlacement:b?.ageAtPlacement===null||b?.ageAtPlacement===undefined?'':b.ageAtPlacement,placementEstimated:!!b?.placementEstimated,status:b?.status||'active',error:''};}
  render(){const s=this.state,change=(k:string,v:any)=>this.setState({[k]:v,error:''});return <form onSubmit={ev=>{ev.preventDefault();try{this.props.onSave({...s,initialBirds:Number(s.initialBirds),chickCost:Number(s.chickCost),ageAtPlacement:s.ageAtPlacement===''?null:Number(s.ageAtPlacement)});}catch(e:any){change('error',e.message);}}}><div className="modal-heading"><h2>{this.props.batch?'Edit batch':'Start a new batch'}</h2><button type="button" className="icon-btn" aria-label="Close" onClick={this.props.onCancel}><Icon name="close"/></button></div><div className="form-grid"><Field label="Batch name" wide><input value={s.name} maxLength={120} required onChange={e=>change('name',e.target.value)} placeholder="e.g. October broilers"/></Field><Field label="Date chicks were purchased"><input type="date" required value={s.placementDate} onChange={e=>change('placementDate',e.target.value)}/></Field><Field label="Date confidence"><select value={String(s.placementEstimated)} onChange={e=>change('placementEstimated',e.target.value==='true')}><option value="false">Known date</option><option value="true">Approximate / needs correction</option></select></Field><Field label="Number of chicks purchased"><input type="number" min="1" step="1" required value={s.initialBirds} onChange={e=>change('initialBirds',e.target.value)}/></Field><Field label="Total chick cost (₱)"><input type="number" min="0" step="0.01" required value={s.chickCost} onChange={e=>change('chickCost',e.target.value)}/></Field><Field label="Chick age at purchase (days)" hint="Leave blank when unknown. The app then uses days since purchase."><input type="number" min="0" max="180" step="1" value={s.ageAtPlacement} onChange={e=>change('ageAtPlacement',e.target.value)}/></Field><Field label="Status"><select value={s.status} onChange={e=>change('status',e.target.value)}><option value="active">Active</option><option value="closed">Closed / harvested</option></select></Field></div>{s.error&&<Note tone="error">{s.error}</Note>}<div className="modal-actions"><button type="button" className="btn secondary" onClick={this.props.onCancel}>Cancel</button><button className="btn primary" type="submit">Save batch</button></div></form>;}
}
function recordDescription(e:any,b:any){const p=b.events.find((x:any)=>x.id===e.lotId);switch(e.type){case'feed':return `${e.kg===null?'kg unknown':qty(e.kg)+' kg'} · ${e.phase} · ${money(e.cost)}${e.kg?' · '+money(e.cost/e.kg,2)+'/kg':''}`;case'usage':return `${qty(e.kg)} kg · ${p?.name||'Feed lot'} · ${dateLabel(e.startDate)} → ${dateLabel(e.date)}`;case'weigh':return `${qty(e.avgKg)} kg average${e.sampleN?' · '+e.sampleN+' weighed':''}${e.maxKg!==null?' · max '+qty(e.maxKg)+' kg':''}`;case'count':return `${e.count} live birds counted`;case'loss':return `${e.count} birds removed`;case'harvest':return `${e.count} birds · ${qty(e.dressedKg)} kg dressed · ${money(e.revenue)} cash`;case'openingUsage':return `${money(e.cost)} historical feed used · no new cash expense`;case'note':return e.note||'Farm note';default:return money(e.cost);}}
const TYPELABEL:any={feed:'Feed purchase',usage:'Feed used',weigh:'Weighing',count:'Live count',loss:'Bird loss',harvest:'Harvest',expense:'Expense',budget:'Budget only',openingUsage:'Historical feed use',note:'Note'};
class App extends React.Component<any,any>{
  constructor(props:any){super(props);let data:any=null,error='';try{const raw=storeRead();data=raw?M.validateState(JSON.parse(raw)):M.seededState();if(!raw)storeWrite(data);}catch(e:any){error=e.message;}
    this.state={data,tab:'overview',modal:null,toast:'',filter:'all',scenarioDraft:null,selectedDay:null,importText:'',importError:'',storageError:error,loadError:!data?error:'',capitalDraft:{name:'',cost:'',date:''}};
  }
  componentDidMount(){(window as any).checkPendingImport=()=>{if(NATIVE){const text=nativeCall('take-import');if(text)(window as any).receiveNativeBackup(text);}};(window as any).receiveNativeBackup=(text:string)=>{this.setState({tab:'backup',importText:text,importError:''});};(window as any).nativeNotice=(s:string)=>this.toast(s);(window as any).nativeBack=()=>{if(this.state.modal){this.setState({modal:null});return true;}if(this.state.tab!=='overview'){this.setState({tab:'overview'});return true;}return false;};window.addEventListener('keydown',this.keydown);(window as any).checkPendingImport();}
  componentWillUnmount(){window.removeEventListener('keydown',this.keydown);}
  keydown=(e:KeyboardEvent)=>{if(e.key==='Escape'&&this.state.modal)this.setState({modal:null});};
  b=()=>this.state.data.batches.find((b:any)=>b.id===this.state.data.selectedBatchId);
  toast=(msg:string)=>{this.setState({toast:msg});setTimeout(()=>this.setState({toast:''}),4200);};
  commit=(data:any,msg='Saved on this device')=>{M.validateState(data);storeWrite(data);this.setState({data,storageError:''});this.toast(msg);};
  mutate=(fn:any,msg?:string)=>{const d=clone(this.state.data);fn(d,d.batches.find((b:any)=>b.id===d.selectedBatchId));this.commit(d,msg);};
  openRecord=(type='weigh',event:any=null,convert:any=null)=>this.setState({modal:{kind:'record',type,event,convert}});
  saveRecord=(record:any)=>{const modal=this.state.modal;this.mutate((d:any,b:any)=>{if(modal.convert)b.events=b.events.filter((e:any)=>e.id!==modal.convert.id);const i=b.events.findIndex((e:any)=>e.id===record.id);if(i>=0)b.events[i]=record;else b.events.push(record);},'Record saved');this.setState({modal:null});};
  deleteRecord=(event:any)=>{if(!window.confirm(`Delete this ${TYPELABEL[event.type].toLowerCase()}? This can change stock and costs.`))return;try{this.mutate((d:any,b:any)=>{b.events=b.events.filter((e:any)=>e.id!==event.id);},'Record deleted');}catch(e:any){this.toast(e.message);}};
  capital=()=>M.sum(this.state.data.settings.capital.map((a:any)=>a.cost));
  projection=()=>M.forecast(this.b(),this.state.scenarioDraft||this.b().forecast,this.capital(),this.state.data.settings.recoveryBatches);
  switchTab=(tab:string)=>{this.setState({tab});window.scrollTo(0,0);};
  renderOverview(){const b=this.b(),s=M.summary(b),perf=M.recentPerformance(b),f=this.projection(),ws=M.records(b,'weigh').filter((e:any)=>e.date),live=M.headcount(b),age=M.days(b.placementDate,M.today());
    const series:any=[{label:'Measured sample',color:'#395a43',markAll:true,points:ws.filter((w:any)=>w.method==='measured').map((w:any)=>({x:M.days(b.placementDate,w.date),y:w.avgKg}))},{label:'Rough estimate',color:'#a57636',connect:false,open:true,points:ws.filter((w:any)=>w.method==='estimate').map((w:any)=>({x:M.days(b.placementDate,w.date),y:w.avgKg}))}];
    if(f.rows.length)series.push({label:'Editable scenario, not a prediction',color:'#788570',dash:true,points:f.rows.map((r:any)=>({x:r.day,y:r.weight}))});
    const recent=b.events.slice().sort((a:any,c:any)=>(c.date||'').localeCompare(a.date||'')).slice(0,4);
    return <><div className="page-title"><div><span className="eyebrow">YOUR FLOCK, AT A GLANCE</span><h1>{b.name}</h1><p>{age<0?'Purchase is in the future':`Day ${age} since purchase`} · {b.placementEstimated?'Approximate purchase date':'Purchased'} {dateLabel(b.placementDate)}{b.ageAtPlacement!==null?` · approximately ${age+b.ageAtPlacement} days old`:''}</p></div><button className="btn secondary small" onClick={()=>this.setState({modal:{kind:'batch',batch:b}})}><Icon name="edit" size={16}/>Edit batch</button></div>
    <div className="metrics"><Metric label="Chicks placed" value={b.initialBirds} sub={`${money(b.chickCost/b.initialBirds)} per chick`}/><Metric label="Live birds" value={live.confirmed?live.count:'Not counted'} sub={live.confirmed?'Last count less recorded removals':`${live.count} on the ledger; survival unverified`}/><Metric label={s.weigh?.method==='estimate'?'Latest weight estimate':'Latest sample average'} value={s.weigh?qty(s.weigh.avgKg)+' kg':'—'} sub={s.weigh?dateLabel(s.weigh.date):'Add your first weighing'}/><Metric label="Batch cash recorded" value={money(s.cashPaid)} sub="Chicks + feed purchases + expenses" accent/></div>
    {(!live.confirmed||!perf||s.inventoryIncomplete)&&<Note tone="warn"><strong>Some important data is still missing.</strong> {!live.confirmed?'Add an actual live-bird count. ':''}{s.inventoryIncomplete?'Earlier feed kilograms are unknown. ':''}{!perf?'Two measured weigh-ins will unlock observed daily gain. ':''}Estimates are never presented as measured growth.</Note>}
    <div className="quick-actions"><button onClick={()=>this.openRecord('weigh')}><Icon name="weight"/><span>Weigh birds</span></button><button onClick={()=>this.openRecord('feed')}><Icon name="feed"/><span>Buy feed</span></button><button onClick={()=>this.openRecord('usage')}><Icon name="log"/><span>Log feed used</span></button><button onClick={()=>this.openRecord('count')}><Icon name="flock"/><span>Count birds</span></button></div>
    <div className="two-col"><section className="card"><SectionTitle title="Live weight over time" sub="Kilograms per bird · dated observations"/>{ws.length?<LineChart series={series.filter((s:any)=>s.points.length)} title="Live weight over time" floorZero/>:<Empty title="Your growth chart starts here" text="Add a dated weighing to see progress."/>}{!perf&&<p className="muted small-text">One estimated point is not a growth curve. No growth rate is inferred from it.</p>}</section>
    <section className="card"><SectionTitle title="Where the money goes" sub="PHP · current selected batch"/>{[['Chicks',b.chickCost],['Feed purchased',s.feedPaid],['Other expenses',s.otherPaid]].map(([label,v]:any)=><div className="cost-bar" key={label}><div><span>{label}</span><strong>{money(v)}</strong></div><div className="bar-track"><div style={{width:Math.max(0,(s.cashPaid?v/s.cashPaid*100:0))+'%'}}/></div></div>)}<div className="totals-row"><span>Separate feed budget</span><strong>{money(s.budgets)}</strong></div><div className="totals-row"><span>Farm infrastructure</span><strong>{money(this.capital())}</strong></div><p className="muted small-text">Budgets are not purchases. Infrastructure is shared across batches, never charged again as feed.</p></section></div>
    <div className="two-col"><section className="card"><SectionTitle title="Feed & production" sub="Only what has been logged"/><div className="detail-grid"><div><small>Known feed bought</small><strong>{qty(s.knownPurchasedKg)} kg{s.inventoryIncomplete?' + unknown':''}</strong></div><div><small>Recorded feed used</small><strong>{qty(s.recordedUsedKg)} kg</strong></div><div><small>Known stock remaining</small><strong>{qty(s.inventoryKg)} kg</strong></div><div><small>Feed-use cost logged</small><strong>{money(s.usedFeed)}</strong></div></div><p className="muted small-text">A blank consumption log does not mean zero feed was eaten. Inventory excludes purchases with unknown kg.</p>{perf&&<Note><strong>{qty(perf.gainG,1)} g/day</strong> observed sample growth ({dateLabel(perf.start)}–{dateLabel(perf.end)}). {perf.fcr!==null?`${qty(perf.fcr)} logged-feed ratio; incomplete usage logs can bias it.`:'No comparable logged-feed ratio is available yet.'}</Note>}</section>
    <section className="card"><SectionTitle title="Harvest results" sub="Actual carcass weights and cash"/><div className="detail-grid"><div><small>Birds harvested</small><strong>{s.harvestedBirds}</strong></div><div><small>Dressed output</small><strong>{qty(s.dressedKg)} kg</strong></div><div><small>Cash received</small><strong>{money(s.revenue)}</strong></div><div><small>Kept for home</small><strong>{qty(s.homeKg)} kg</strong></div></div>{s.dressedKg>0&&<Note>Purchase-based cost to date: <strong>{money(s.cashPaid/s.dressedKg,2)}/harvested kg</strong>. {s.head.count>0?'This includes costs of birds still growing, so it is not a final batch unit cost.':'Includes all paid feed, even unused inventory; excludes the pen.'}</Note>}<button className="text-btn" onClick={()=>this.openRecord('harvest')}>Record a harvest <Icon name="arrow" size={16}/></button></section></div>
    <section className="card"><SectionTitle title="Latest entries" action={<button className="text-btn" onClick={()=>this.switchTab('records')}>All records <Icon name="arrow" size={16}/></button>}/>{recent.map((e:any)=><div className="recent-row" key={e.id}><div><Badge kind={e.type==='budget'||e.method==='estimate'?'warn':'muted'}>{TYPELABEL[e.type]}</Badge><strong>{e.name||TYPELABEL[e.type]}</strong><small>{recordDescription(e,b)}</small></div><span className="date">{dateLabel(e.date)}</span></div>)}</section>
    </>;
  }
  renderRecords(){const b=this.b(),events=b.events.filter((e:any)=>this.state.filter==='all'||e.type===this.state.filter).sort((a:any,c:any)=>(c.date||'').localeCompare(a.date||'')),inv=M.feedInventory(b);
    return <><div className="page-title"><div><span className="eyebrow">THE FARM LOGBOOK</span><h1>Every entry, dated.</h1><p>Purchases, consumption, weights, counts and harvests in one place.</p></div><button className="btn primary" onClick={()=>this.openRecord('feed')}><Icon name="plus"/>Add record</button></div>
    <section className="card"><div className="filter-row"><label>Show <select aria-label="Filter records" value={this.state.filter} onChange={e=>this.setState({filter:e.target.value})}><option value="all">All records</option>{Object.entries(TYPELABEL).map(([v,l])=><option key={v} value={v}>{l as string}</option>)}</select></label><span className="muted">{events.length} entries</span></div>{!events.length?<Empty title="No entries here yet" text="Add a record for this batch."/>:events.map((e:any)=><article className="record" key={e.id}><div className="record-top"><Badge kind={e.type==='budget'||e.method==='estimate'?'warn':'muted'}>{e.type==='weigh'&&e.method==='estimate'?'Estimated weight':TYPELABEL[e.type]}</Badge><span>{dateLabel(e.date)}</span></div><h3>{e.name||TYPELABEL[e.type]}</h3><p>{recordDescription(e,b)}</p>{e.note&&e.type!=='note'&&<p className="record-note">{e.note}</p>}<div className="record-buttons">{e.type==='budget'&&<button className="text-btn" onClick={()=>this.openRecord('feed',null,e)}>Convert to purchase <Icon name="arrow" size={15}/></button>}<div className="spacer"/><button className="icon-btn" title="Edit record" aria-label={'Edit '+(e.name||TYPELABEL[e.type])} onClick={()=>this.openRecord(e.type,e)}><Icon name="edit" size={17}/></button><button className="icon-btn danger" title="Delete record" aria-label={'Delete '+(e.name||TYPELABEL[e.type])} onClick={()=>this.deleteRecord(e)}><Icon name="trash" size={17}/></button></div></article>)}</section>
    <section className="card"><SectionTitle title="Feed inventory" sub="By purchase lot · unknown quantities are not filled in"/><div className="table-wrap"><table><thead><tr><th>Feed / lot</th><th>Bought kg</th><th>Used kg</th><th>Left kg</th><th>₱/kg</th></tr></thead><tbody>{inv.map((p:any)=><tr key={p.id}><td>{p.name}<small>{dateLabel(p.date)}</small></td><td>{qty(p.kg)}</td><td>{qty(p.used)}</td><td>{qty(p.remaining)}</td><td>{money(p.price,2)}</td></tr>)}</tbody></table></div><p className="muted small-text">Historical feed-use adjustments do not deduct kilograms from specific lots. Use them only for untracked historical feed; reconcile old stock before claiming complete inventory.</p></section></>;
  }
  forecastInput=(key:string,label:string,hint:string,step:any='any')=>{const p=this.state.scenarioDraft||this.b().forecast;return <Field label={label} hint={hint}><input type="number" min="0" step={step} inputMode="decimal" value={p[key]===null?'':p[key]} onChange={e=>this.setState({scenarioDraft:{...p,[key]:e.target.value===''?null:Number(e.target.value)}})}/></Field>;};
  saveScenario=()=>{try{const p=this.state.scenarioDraft||this.b().forecast;this.mutate((d:any,b:any)=>{b.forecast=clone(p);},'Scenario saved');this.setState({scenarioDraft:null});}catch(e:any){this.toast(e.message);}};
  renderForecast(){const b=this.b(),p=this.state.scenarioDraft||b.forecast,f=this.projection(),s=M.summary(b,p.startDate||M.today()),perf=M.recentPerformance(b);const chosen=f.rows.find((r:any)=>r.day===this.state.selectedDay)||f.best;const important=f.rows.filter((r:any)=>[f.startDay,35,38,40,42,45,47,49,52,56,60,70,84,p.endDay,f.best?.day,this.state.selectedDay].includes(r.day));
    return <><div className="page-title"><div><span className="eyebrow">HARVEST PLANNER</span><h1>The cost of another week.</h1><p>Compare slaughter dates using explicit, editable assumptions.</p></div><Badge kind="warn">Scenario, not a guarantee</Badge></div><Note tone="warn">The earlier chat curves were illustrations, not measured forecasts. This planner does not assume 47 survivors, ₱30/kg feed, or a guaranteed day-52 optimum. Supply the missing values below.</Note>
    <section className="card"><SectionTitle title="Your starting point" sub="The cost and flock state must refer to the same date."/><div className="form-grid three"><Field label="Projection start date"><input type="date" min={b.placementDate} value={p.startDate||''} onChange={e=>this.setState({scenarioDraft:{...p,startDate:e.target.value}})}/></Field>{this.forecastInput('birds','Birds remaining at start','Required; use a real count or an explicitly chosen scenario.',1)}{this.forecastInput('weightKg','Average live weight at start (kg)','Use a weighed sample average. Rough estimates are not measured samples.')}{this.forecastInput('baselineCost','Operating cost USED by start (₱)','Chicks + feed already used + other costs. Exclude unused feed, budgets and the pen.')}{this.forecastInput('feedPrice','Future feed price (₱ per kg)','Enter your actual purchase price, or your chosen scenario price.')}{this.forecastInput('yieldPct','Dressed yield (%)','70% is an editable illustration. Actual yield comes from harvest records.')}</div>
    <div className="button-row"><button className="btn secondary small" onClick={()=>{const w=M.latestWeigh(b);if(!w){this.toast('Add a weighing first.');return;}const h=M.headcount(b,w.date),inv=M.feedInventory(b).filter((p:any)=>p.price!==null).sort((a:any,b:any)=>(a.date||'').localeCompare(b.date||'')||(a.createdAt||'').localeCompare(b.createdAt||''));const next={...p,startDate:w.date,weightKg:w.avgKg};if(h.confirmed)next.birds=h.count;if(inv.length)next.feedPrice=inv[inv.length-1].price;this.setState({scenarioDraft:next});this.toast('Copied the latest weight; only a verified count and known feed price were copied.');}}>Use latest records</button><button className="btn secondary small" onClick={()=>this.setState({scenarioDraft:{...p,baselineCost:s.usedOperating}})}>Use logged production costs ({money(s.usedOperating)})</button></div><p className="muted small-text">Logged production costs may be incomplete. Include only chicks, feed already used, and other incurred costs at the projection start. Exclude unused feed, future budgets, and shared infrastructure.</p>
    <details className="assumptions" open><summary>Growth, feed conversion and pricing assumptions</summary><p className="muted small-text">The starting presets below are arbitrary planning inputs, not strain targets or a fitted biological growth model. They do not predict catch-up growth.</p><div className="form-grid three">{this.forecastInput('gainG','Starting live gain (g/bird/day)','Illustrative 60 g; replace with your measured gain.')}{this.forecastInput('gainDeclinePct','Daily reduction in gain (%)','Compounded each day. 0 means constant growth.')}{this.forecastInput('fcr','Starting incremental FCR','Feed kg used per extra live kg, not lifetime FCR.')}{this.forecastInput('fcrRise','FCR increase per extra day','Linear change. 0 means constant feed efficiency.')}{this.forecastInput('dailyOther','Extra daily costs for whole flock (₱)','Labor, transport or electricity not already in the starting cost.')}{this.forecastInput('endDay','Compare through day since purchase','A day number, NOT days from today.',1)}{this.forecastInput('salePrice','Dressed sale / replacement price (₱/kg)','Optional. Home-use savings are not cash revenue.')}{this.forecastInput('downtime','Days between repeat batches','Cleaning, drying and scheduling time.',1)}</div>{perf&&<button className="text-btn" onClick={()=>{if(perf.gainG<=0){this.toast('Recent measured gain is not positive; forecasts require a positive scenario.');return;}this.setState({scenarioDraft:{...p,gainG:Math.round(perf.gainG*10)/10}});}}>Use recent measured gain: {qty(perf.gainG,1)} g/day</button>}</details>
    <div className="button-row"><button className="btn primary" onClick={this.saveScenario}><Icon name="save" size={17}/>Save scenario</button>{this.state.scenarioDraft&&<button className="btn secondary" onClick={()=>this.setState({scenarioDraft:null})}>Discard unsaved changes</button>}</div></section>
    {f.errors.length>0?<section className="card"><Empty title="Complete the scenario to see the curves" text="No costs or harvest date will be invented for missing inputs."/><div className="requirements">{f.errors.map((e:string,i:number)=><p key={i}>{e}</p>)}</div></section>:<>
    <div className="metrics"><Metric label="Lowest within this scenario" value={money(f.best.perKg,2)+'/kg'} sub={`Day ${f.best.day} · ${dateLabel(f.best.date)}`} accent/><Metric label="Within 1% of that low" value={`Days ${f.nearBest[0].day}–${f.nearBest[f.nearBest.length-1].day}`} sub="Cost differences here are small"/><Metric label="Scenario weight at the low" value={qty(f.best.weight)+' kg'} sub="Average live kg per remaining bird"/><Metric label="More feed to reach it" value={qty(f.best.feedKg,1)+' kg'} sub={`${money(f.best.feedCost)} of feed used after start`}/></div>
    {f.atBoundary&&<Note tone="warn">The lowest modeled cost is at the edge of your selected date range. This does not establish an interior optimum or a biological harvest recommendation.</Note>}
    {b.events.some((e:any)=>e.type==='harvest')&&<Note tone="warn">This is a forward scenario for the remaining birds only. Allocate the starting cost to those birds; do not load the full batch cost after a partial harvest. The app does not infer that allocation.</Note>}
    <section className="card"><SectionTitle title="Operating cost per dressed kilogram" sub={`${p.birds} birds · ${p.yieldPct}% dressed yield · no future deaths modeled`}/><LineChart unit="₱/kg" title="Projected cost per dressed kilogram" series={[{label:'Operating cost only',color:'#395a43',points:f.rows.map((r:any)=>({x:r.day,y:r.perKg}))},{label:`Including pen recovery over ${this.state.data.settings.recoveryBatches} batches`,color:'#a57636',dash:true,points:f.rows.map((r:any)=>({x:r.day,y:r.fullPerKg}))}]}/><Note>Further growth lowers the average cost only while <strong>marginal cost/kg is below the existing average cost/kg</strong>. A low scenario cost does not establish health, welfare or market suitability.</Note></section>
    <section className="card"><SectionTitle title="Compare slaughter dates" sub="Tap a row to update the annual comparison. All rows are modeled, not observations."/><Field label="Harvest date for annual comparison"><select value={chosen.day} onChange={e=>this.setState({selectedDay:Number(e.target.value)})}>{f.rows.map((r:any)=><option value={r.day} key={r.day}>Day {r.day} · {dateLabel(r.date)} · {money(r.perKg,2)}/kg</option>)}</select></Field><div className="table-wrap"><table className="forecast-table"><thead><tr><th>Day / date</th><th>Live kg/bird</th><th>Extra feed kg</th><th>Operating ₱</th><th>Dressed kg</th><th>Operating ₱/kg</th><th>Next-day marginal ₱/kg*</th></tr></thead><tbody>{important.map((r:any)=>{const next=f.rows.find((n:any)=>n.day===r.day+1);return <tr key={r.day} className={r.day===chosen.day?'selected':''} onClick={()=>this.setState({selectedDay:r.day})}><td><button className="day-pick" aria-label={'Select day '+r.day}>Day {r.day}</button><small>{dateLabel(r.date)}</small>{r.day===f.best.day&&<Badge kind="green">Scenario low</Badge>}</td><td>{qty(r.weight)}</td><td>{qty(r.feedKg,1)}</td><td>{money(r.cost)}</td><td>{qty(r.dressed,1)}</td><td><strong>{money(r.perKg,2)}</strong></td><td>{next?money(next.marginal,2):'—'}</td></tr>;})}</tbody></table></div><p className="muted small-text">*Cost of the additional dressed gain during the next modeled day. Extra feed is cumulative from the projection start. It is feed consumed, not necessarily new feed to purchase.</p><div className="button-row"><button className="btn secondary small" onClick={()=>this.exportForecast(f.rows)}>Export daily comparison CSV</button></div></section>
    <section className="card annual"><SectionTitle title={`Repeat-batch economics · day ${chosen.day}`} sub="365-day capacity scenario, not a calendar schedule or promised profit"/><div className="metrics compact"><Metric label="Full cycles in 365 days" value={chosen.cycles} sub={`${chosen.day} days growing + ${p.downtime} days turnaround each`}/><Metric label="Recurring batch cost" value={money(chosen.cost)} sub="Repeats this exact operating-cost scenario"/><Metric label="First-year break-even" value={money(chosen.annualBreakEven,2)+'/kg'} sub="Includes one full recovery of farm capital"/><Metric label="First-year cash margin*" value={money(chosen.annualMargin)} sub={p.salePrice===null?'Enter a selling price above':'After one capital recovery; listed costs only'}/></div><div className="detail-grid"><div><small>Annual dressed output</small><strong>{qty(chosen.annualKg,1)} kg</strong></div><div><small>Annual recurring cost</small><strong>{money(chosen.annualCost)}</strong></div><div><small>Capital recovered once</small><strong>{money(this.capital())}</strong></div><div><small>Per-batch operating margin*</small><strong>{money(chosen.margin)}</strong></div></div><p className="small-text muted">*Only cash profit if every modeled dressed kilogram is sold at the entered price. For home use it is replacement-value savings, not cash income. Excludes any labor, utilities, losses, taxes, selling or processing costs you have not entered. No overlapping flocks; downtime after each full cycle is counted conservatively. Repeating this batch's partial-age starting cost is a deliberate scenario, not a prediction for future flocks.</p></section>
    <section className="card"><SectionTitle title="How this is calculated"/><div className="formula">Daily gain = starting gain × (1 − daily decline)<sup>days elapsed</sup><br/>Extra feed = live birds × daily live gain × incremental FCR<br/>Operating cost = starting used cost + extra feed cost + extra daily costs<br/>Dressed kg = live birds × projected average live kg × yield<br/>Cost/kg = operating cost ÷ dressed kg</div><p className="muted small-text">Weights, gain and FCR here are explicit assumptions. No automatic breeding-strain curve, compensatory-growth claim or age-specific nutritional prescription is built in. Costs can rise beyond the feed budget.</p></section>
    </> }</>;
  }
  exportForecast=(rows:any[])=>{const keys=['day','date','weight','feedKg','cost','dressed','perKg','fullPerKg','marginal','cycles','annualBreakEven','annualMargin'];let csv=keys.join(',')+'\n'+rows.map(r=>keys.map(k=>r[k]===null?'':typeof r[k]==='number'?r[k].toFixed(4):r[k]).join(',')).join('\n');try{saveDownload('flock-ledger-forecast.csv',csv,'text/csv');}catch(e:any){this.toast(e.message);}};
  renderBatches(){const d=this.state.data;return <><div className="page-title"><div><span className="eyebrow">ONE PEN. MANY BATCHES.</span><h1>Batch history & capital</h1><p>Keep each flock's records separate and reuse the infrastructure.</p></div><button className="btn primary" onClick={()=>this.setState({modal:{kind:'batch'}})}><Icon name="plus"/>New batch</button></div><div className="batch-grid">{d.batches.map((b:any)=>{const s=M.summary(b),selected=b.id===d.selectedBatchId;return <section className={'card batch-card '+(selected?'active':'')} key={b.id}><Badge kind={b.status==='active'?'green':'muted'}>{b.status}</Badge><h2>{b.name}</h2><p>{dateLabel(b.placementDate)}{b.placementEstimated?' · approximate':''}</p><div className="detail-grid"><div><small>Placed</small><strong>{b.initialBirds} birds</strong></div><div><small>Cash recorded</small><strong>{money(s.cashPaid)}</strong></div><div><small>Dressed output</small><strong>{qty(s.dressedKg)} kg</strong></div><div><small>Cash received</small><strong>{money(s.revenue)}</strong></div></div><div className="button-row"><button className={'btn small '+(selected?'secondary':'primary')} onClick={()=>{try{this.mutate((d:any)=>{d.selectedBatchId=b.id;});this.setState({scenarioDraft:null,selectedDay:null,tab:'overview'});}catch(e:any){this.toast(e.message);}}}>{selected?'Open current batch':'Open batch'}</button><button className="icon-btn" aria-label={'Edit '+b.name} onClick={()=>this.setState({modal:{kind:'batch',batch:b}})}><Icon name="edit"/></button></div></section>;})}</div>
    <section className="card"><SectionTitle title="Shared infrastructure" sub="One-time purchases, separate from feed and chicks."/><div className="table-wrap"><table><thead><tr><th>Item</th><th>Date</th><th>Cost</th><th/></tr></thead><tbody>{d.settings.capital.map((a:any)=><tr key={a.id}><td>{a.name}</td><td>{dateLabel(a.date)}</td><td>{money(a.cost)}</td><td><button className="icon-btn danger" aria-label={'Remove capital '+a.name} onClick={()=>{if(!window.confirm('Remove this infrastructure record?'))return;try{this.mutate((d:any)=>{d.settings.capital=d.settings.capital.filter((x:any)=>x.id!==a.id);});}catch(e:any){this.toast(e.message);}}}><Icon name="trash" size={16}/></button></td></tr>)}</tbody></table></div><form onSubmit={e=>{e.preventDefault();const c=this.state.capitalDraft;try{this.mutate((d:any)=>{d.settings.capital.push({id:M.uid(),name:c.name,date:c.date||null,cost:Number(c.cost)});});this.setState({capitalDraft:{name:'',cost:'',date:''}});}catch(err:any){this.toast(err.message);}}}><div className="form-grid three"><Field label="New infrastructure item"><input required maxLength={180} value={this.state.capitalDraft.name} onChange={e=>this.setState({capitalDraft:{...this.state.capitalDraft,name:e.target.value}})}/></Field><Field label="Amount (₱)"><input required type="number" min="0" step="0.01" value={this.state.capitalDraft.cost} onChange={e=>this.setState({capitalDraft:{...this.state.capitalDraft,cost:e.target.value}})}/></Field><Field label="Purchase date (optional)"><input type="date" value={this.state.capitalDraft.date} onChange={e=>this.setState({capitalDraft:{...this.state.capitalDraft,date:e.target.value}})}/></Field></div><button className="btn secondary small" type="submit">Add infrastructure</button></form><hr/><Field label="Batches over which to show capital recovery" hint="A planning allocation, not tax depreciation. This never changes operating-only cost/kg."><input type="number" min="1" max="1000" step="1" value={d.settings.recoveryBatches} onChange={e=>{const n=Number(e.target.value);if(Number.isInteger(n)&&n>0&&n<=1000){try{this.mutate((d:any)=>{d.settings.recoveryBatches=n;});}catch(err:any){this.toast(err.message);}}}}/></Field><p>At {d.settings.recoveryBatches} batches, shared capital adds <strong>{money(this.capital()/d.settings.recoveryBatches,2)} per batch</strong> to the full-cost scenario, before dividing by dressed kilograms.</p></section></>;
  }
  backup=()=>{try{saveDownload('flock-ledger-backup-'+M.today()+'.json',JSON.stringify(this.state.data,null,2));if(!NATIVE)this.toast('Backup download started');}catch(e:any){this.toast(e.message);}};
  importBackup=()=>{try{const raw=this.state.importText;if(raw.length>4500000)throw new Error('Backup exceeds the 4.5 MB import limit.');const d=M.validateState(JSON.parse(raw));if(!window.confirm(`Replace the ledger on THIS device with ${d.batches.length} batch(es) from the backup? Export the current ledger first to keep it.`))return;this.commit(d,'Backup restored');this.setState({importText:'',importError:'',scenarioDraft:null,selectedDay:null,filter:'all'});}catch(e:any){this.setState({importError:e.message});}};
  chooseBackup=()=>{if(NATIVE){const result=nativeCall('import');if(result!=='pending')this.toast(result||'Import could not start.');}else(document.getElementById('backup-file') as HTMLInputElement).click();};
  renderBackup(){return <><div className="page-title"><div><span className="eyebrow">YOUR DATA STAYS YOURS</span><h1>Backup & transfer</h1><p>Offline storage on this device. No account, subscription or cloud service.</p></div><Badge kind="green">{NATIVE?'Android local storage':'Browser local storage'}</Badge></div>
    <Note tone="warn"><strong>Phone and tablet do not automatically sync.</strong> Export a JSON backup on the device with the newest data, then import it on the other device. Import replaces the whole local ledger; it does not merge records. Back up before uninstalling or clearing app data.</Note>
    <div className="two-col"><section className="card"><SectionTitle title="Save a backup" sub="All batches, entries, scenarios and infrastructure"/><p>Keep a dated JSON copy outside the app. You can restore it or transfer it to your other device.</p><button className="btn primary" onClick={this.backup}><Icon name="save"/>Export JSON backup</button></section><section className="card"><SectionTitle title="Restore or transfer" sub="Choose a backup file or paste its contents"/><button className="btn secondary" onClick={this.chooseBackup}>Choose JSON backup file</button><input hidden id="backup-file" type="file" accept=".json,application/json" onChange={e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>4500000){this.setState({importError:'Backup exceeds 4.5 MB.'});return;}const reader=new FileReader();reader.onload=()=>this.setState({importText:String(reader.result),importError:''});reader.onerror=()=>this.setState({importError:'Could not read this file.'});reader.readAsText(file);e.target.value='';}}/><Field label="Backup JSON" wide><textarea rows={6} spellCheck={false} value={this.state.importText} placeholder="Paste a Flock Ledger backup here…" onChange={e=>this.setState({importText:e.target.value,importError:''})}/></Field>{this.state.importError&&<Note tone="error">{this.state.importError}</Note>}<button className="btn primary" disabled={!this.state.importText.trim()} onClick={this.importBackup}>Validate & restore backup</button></section></div>
    <section className="card"><SectionTitle title="About this build" sub="Flock Ledger 1.0 · private offline edition"/><p>Records and calculations run entirely on your device. The APK has no internet permission, analytics or advertising. No feed-price service or market-price feed is connected.</p><div className="detail-grid"><div><small>Currency</small><strong>Philippine pesos</strong></div><div><small>Date basis</small><strong>Device-local calendar dates</strong></div><div><small>Measured vs modeled</small><strong>Always labeled separately</strong></div><div><small>Weight basis</small><strong>Live and dressed kept separate</strong></div></div><hr/><h3>What “cost” means here</h3><p><strong>Recorded cash:</strong> chicks + feed purchases + expenses. Unused feed still belongs in this cash total.</p><p><strong>Logged production cost:</strong> chicks + priced feed-use logs + historical feed-use adjustments + expenses. Missing logs make this incomplete.</p><p><strong>Forecast cost:</strong> your entered starting production cost plus modeled future feed use and daily expenses. Budgets and shared capital are not silently added.</p><p><strong>Capital recovery:</strong> a separate allocation across your selected number of batches. First-year comparisons recover the shared capital once.</p><p><strong>Data quality:</strong> purchase date may be approximate; age at purchase, survivors, feed quantity and weights can remain unknown. No breed growth targets are embedded.</p></section>
    </>;
  }
  render(){const s=this.state;if(!s.data)return <main className="recovery"><h1>Your saved ledger could not be opened</h1><Note tone="error">{s.loadError}</Note><p>No stored data has been overwritten. Close and reopen the app, or restore a valid JSON backup. Keep a copy of the original data before replacing it.</p><textarea id="recovery-raw" readOnly rows={8} value={(()=>{try{return storeRead()||'';}catch(e){return '';}})()}/><p>Raw saved data is shown above for recovery.</p>{NATIVE&&<button className="btn secondary" onClick={this.chooseBackup}>Choose a JSON backup</button>}<Field label="Paste or selected backup"><textarea rows={6} value={s.importText} onChange={e=>this.setState({importText:e.target.value,importError:''})}/></Field>{s.importError&&<Note tone="error">{s.importError}</Note>}<button className="btn primary" disabled={!s.importText.trim()} onClick={this.importBackup}>Validate and restore</button></main>;
    if(!s.data.batches.length)return <main className="recovery">
      <span className="eyebrow">FLOCK LEDGER · OFFLINE RECORDS</span>
      <h1>Start your flock ledger</h1>
      <p>This public build starts empty. Enter your own batch details, or restore your private JSON backup. No farm records are bundled.</p>
      {s.storageError&&<Note tone="error">{s.storageError}</Note>}
      {s.tab==='backup'?<><button className="btn secondary" onClick={()=>this.setState({tab:'overview'})}>Create a batch instead</button>{this.renderBackup()}</>:<>
        <section className="card"><BatchForm onCancel={()=>this.setState({tab:'backup'})} onSave={(values:any)=>{this.mutate((d:any)=>{const b=M.makeBatch(values);d.batches.push(b);d.selectedBatchId=b.id;},'First batch saved');this.setState({tab:'overview',scenarioDraft:null,selectedDay:null});}}/></section>
        <button className="btn secondary" onClick={()=>this.setState({tab:'backup'})}>Restore an existing backup</button>
      </>}
      {s.toast&&<div className="toast" role="status">{s.toast}</div>}
    </main>;
    const b=this.b();const tabs=[['overview','home','Overview'],['records','log','Records'],['forecast','chart','Forecast'],['batches','flock','Batches'],['backup','save','Backup']];
    return <div className="app"><aside className="sidebar"><div className="wordmark"><div className="brand-symbol"><Icon name="flock" size={28}/></div><div>FLOCK<span>LEDGER</span></div></div><p className="side-caption">Know your flock.<br/>Know your real costs.</p><nav aria-label="Main navigation">{tabs.map(([key,icon,label])=><button key={key} className={s.tab===key?'active':''} onClick={()=>this.switchTab(key)}><Icon name={icon}/><span>{label}</span></button>)}</nav><div className="side-footer"><span className="status-dot"/>Works offline<small>PRIVATE FARM EDITION · 1.0</small></div></aside>
    <div className="workspace"><header className="topbar"><div className="mobile-brand"><Icon name="flock" size={23}/>Flock Ledger</div><div className="batch-selector"><span className="eyebrow">BATCH</span><select aria-label="Selected batch" value={b.id} onChange={e=>{try{this.mutate((d:any)=>{d.selectedBatchId=e.target.value;});this.setState({scenarioDraft:null,selectedDay:null,filter:'all'});}catch(err:any){this.toast(err.message);}}}>{s.data.batches.map((b:any)=><option key={b.id} value={b.id}>{b.name}{b.status==='closed'?' · closed':''}</option>)}</select></div><div className="top-date">{dateLabel(M.today())}<span><i className="status-dot"/>Saved locally</span></div><button className="header-add" aria-label="Add record" onClick={()=>this.openRecord()}><Icon name="plus"/></button></header>
    <main>{s.storageError&&<Note tone="error">{s.storageError}</Note>}{s.tab==='overview'?this.renderOverview():s.tab==='records'?this.renderRecords():s.tab==='forecast'?this.renderForecast():s.tab==='batches'?this.renderBatches():this.renderBackup()}<footer>Flock Ledger · {b.name} · Private, offline records</footer></main></div>
    <nav className="bottom-nav" aria-label="Mobile navigation">{tabs.map(([key,icon,label])=><button key={key} className={s.tab===key?'active':''} onClick={()=>this.switchTab(key)}><Icon name={icon}/><span>{label}</span></button>)}</nav>
    {s.toast&&<div className="toast" role="status"><Icon name="check" size={18}/>{s.toast}</div>}
    {s.modal&&<div className="modal-backdrop" role="presentation" onClick={e=>{if(e.target===e.currentTarget)this.setState({modal:null});}}><section role="dialog" aria-modal="true" aria-label={s.modal.kind==='record'?'Record editor':'Batch editor'} className="modal">{s.modal.kind==='record'?<RecordForm key={(s.modal.event?.id||'new')+(s.modal.convert?.id||'')+s.modal.type} type={s.modal.type} event={s.modal.event||(s.modal.convert?{...s.modal.convert,id:undefined,type:'feed',kg:null,phase:'finisher',date:M.today(),note:''}:null)} convert={s.modal.convert} batch={b} onSave={this.saveRecord} onCancel={()=>this.setState({modal:null})}/>:<BatchForm batch={s.modal.batch} onCancel={()=>this.setState({modal:null})} onSave={(values:any)=>{this.mutate((d:any)=>{if(s.modal.batch){const index=d.batches.findIndex((x:any)=>x.id===s.modal.batch.id);d.batches[index]={...d.batches[index],...values};delete d.batches[index].error;}else{const n=M.makeBatch(values);d.batches.push(n);d.selectedBatchId=n.id;}});this.setState({modal:null,scenarioDraft:null,selectedDay:null});}}/>}</section></div>}
    </div>;
  }
}
ReactDOM.render(<App/>,document.getElementById('root'));
